# Generated by Django 6.1 on 2026-08-10 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('career_objective', models.TextField(blank=True)),
                ('profile_strength', models.PositiveIntegerField(default=0)),
                ('career_score', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
